development:
  adapter: mysql2
  database: app_backend
  encoding: utf8
  username: root
  password: 'IKuQVhGw'
  host: 127.0.0.1
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  encoding: utf8
  database: baye_test
  username: root
  password: 'IKuQVhGw'
  host: 127.0.0.1
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: baye
  encoding: utf8
  username: root
  password: 'IKuQVhGw'
  host: 127.0.0.1
  pool: 5
  timeout: 5000
